---
- name: This is a hello-world example
  hosts: all 
  
  tasks:
      
    - name: list server hostname
      shell: "uname -n"
      register: hostname_machine

    - debug:
        msg: "hostname is {{ fqdn }}.  Varibale is set at  {{ set_at }}. Inventory_hostname is  {{ inventory_hostname }} "

